### ISSUE TITLE
Under Fedora it force me to run `microcom` as root

### ISSUE THREAD

**Issue by EugenWiens** [pengutronix/microcom#26]
https://github.com/pengutronix/microcom/blob/7e1206af07ba87a1882733b37e78a08ae4e7d71e/serial.c#L187

```bash
$ ll /var/lock/
insgesamt 4
-rw-r--r--. 1 root root 22  5. Nov 18:22 asound.state.lock
drwx------. 2 root root 60  5. Nov 18:22 iscsi
drwxrwxr-x. 2 root lock 40  5. Nov 18:22 lockdev
drwx------. 2 root root 40  5. Nov 18:22 lvm
drwxr-xr-x. 2 root root 40  5. Nov 18:22 ppp
drwxr-xr-x. 2 root root 40  5. Nov 18:22 subsys
```
is it possible to move the lock to the `lockdev`? Than it is necessary to be in the group `dialout` and `lockdev` but it is better as start it as `root`. Under Ubuntu the folder `/var/lock` is linked to subfolder of `/run`.

**Comment by ukleinek** [comment]
I wonder how minicom behaves here.

**Comment by lynxeye-dev** [comment]
minicom useses lockdev, though it doesn't link to the library, but execve /usr/sbin/lockdev which seems a bit strange.

**Comment by ukleinek** [comment]
Neither `/usr/sbin/lockdev` nor a liblockdev seem to exist in the Debian universe. Where does `lockdev` put the lockfile?

Without liblockdev minicom's configure picks the first directory of the list
`/etc/locks /var/lock /usr/spool/locks /var/spool/locks /var/spool/lock /usr/spool/uucp /var/spool/uucp /var/run`
that exists.

**Comment by lynxeye-dev** [comment]
https://github.com/pengutronix/microcom/pull/28 Works for me, but is a quick shot and I don't know if I'm overlooking something obvious here.

**Comment by EugenWiens** [comment]
I will test it on my system an come back with the results.

Lucas Stach ***@***.***> schrieb am Fr., 28. Mai 2021, 17:19:

**Comment by EugenWiens** [comment]
#28 works for me, with your changes @lynxeye-dev I can use `microcom` without root privileges or the force mode. :+1:

**Comment by ukleinek** [comment]
As https://github.com/pengutronix/microcom/pull/28 was merged, I'm closing this issue.
