### ISSUE TITLE
Sending Ctrl+\ escape code to nested Microcom instance

### ISSUE THREAD

**Issue by richnetdesign** [pengutronix/microcom#35]
I launched a microcom instance on a embedded / busybox device, while connected to it using microcom

When I try Ctrl+\ it is handled by the top level instance.  

I was wondering if there is a mechanism to send escape sequence to a nested Microcom.

**Comment by a3f** [comment]
What's the output of `microcom --version`?

**Comment by richnetdesign** [comment]
On my host I am using `2019.01.0` compiled from this repository.
The embedded device has busybox microcom.  

Based on the specificity of your question and me remembering the two microcoms are different I was able to solve my problem because busybox uses a different escape code Ctrl+x.   I am guessing it isn't a mistake they are different :+1: 

So I think I can close this.

**Comment by richnetdesign** [comment]
If I did have two identical microcom's nested I expect it would just be 
```
Ctrl+/
Ctrl+/ quit
```
but I am not setup to verify that right now
