### ISSUE TITLE
Regression with Labgrid client console -l (Loop Command)

### ISSUE THREAD

**Issue by Emantor** [pengutronix/microcom#7]
bfcf9a9f00be03db3039b6e5a27b710429fef75e introduces a regression with labgrid. The -l argument for the console command only restarts on exit codes other than zero. See [client.py](https://github.com/labgrid-project/labgrid/blob/dd2fa9bc1bfd152c2ba837c10b808fb3c7e7a9a2/labgrid/remote/client.py#L677) for reference.

**Comment by ukleinek** [comment]
Not sure what to do here. I think it's an error if the remote end closes the connection, but I wonder if there are non-error cases where `read` hits `EOF`

**Comment by jluebbe** [comment]
With EOF, you mean a read() returning 0 bytes? That's the normal behavior if the other side calls shutdown() or close(). What we need from the labgrid side is a way to distinguish an exit requested by the local user from the other exit reasons.
